version: "3.9"

services:
  golang:
    build: './'
    volumes:
      - ./cmd:/cmd
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - "7000:7000"
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "-t", "600000000", "--", "/build"]


  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "friendly_sport"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  redis:
    image: "redis"
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - cache:/data



volumes:
  cache:
    driver: local

