// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: pkg/workout/pb/workout/workout.proto

package workout

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExerciseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	WorkoutId   uint64 `protobuf:"varint,2,opt,name=workout_id,json=workoutId,proto3" json:"workout_id"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
}

func (x *CreateExerciseRequest) Reset() {
	*x = CreateExerciseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExerciseRequest) ProtoMessage() {}

func (x *CreateExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExerciseRequest.ProtoReflect.Descriptor instead.
func (*CreateExerciseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExerciseRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateExerciseRequest) GetWorkoutId() uint64 {
	if x != nil {
		return x.WorkoutId
	}
	return 0
}

func (x *CreateExerciseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateExerciseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateExerciseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   uint32    `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Error    string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
	Exercise *Exercise `protobuf:"bytes,3,opt,name=exercise,proto3" json:"exercise"`
}

func (x *CreateExerciseResponse) Reset() {
	*x = CreateExerciseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExerciseResponse) ProtoMessage() {}

func (x *CreateExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExerciseResponse.ProtoReflect.Descriptor instead.
func (*CreateExerciseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExerciseResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateExerciseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateExerciseResponse) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type UpdateExerciseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId    uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	WorkoutId uint64 `protobuf:"varint,3,opt,name=workout_id,json=workoutId,proto3" json:"workout_id"`
	Query     []byte `protobuf:"bytes,4,opt,name=query,proto3" json:"query"`
}

func (x *UpdateExerciseRequest) Reset() {
	*x = UpdateExerciseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExerciseRequest) ProtoMessage() {}

func (x *UpdateExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExerciseRequest.ProtoReflect.Descriptor instead.
func (*UpdateExerciseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateExerciseRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateExerciseRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateExerciseRequest) GetWorkoutId() uint64 {
	if x != nil {
		return x.WorkoutId
	}
	return 0
}

func (x *UpdateExerciseRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type UpdateExerciseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   uint32    `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Error    string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
	Exercise *Exercise `protobuf:"bytes,3,opt,name=exercise,proto3" json:"exercise"`
}

func (x *UpdateExerciseResponse) Reset() {
	*x = UpdateExerciseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExerciseResponse) ProtoMessage() {}

func (x *UpdateExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExerciseResponse.ProtoReflect.Descriptor instead.
func (*UpdateExerciseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateExerciseResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateExerciseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateExerciseResponse) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type DeleteExerciseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId    uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	WorkoutId uint64 `protobuf:"varint,3,opt,name=workout_id,json=workoutId,proto3" json:"workout_id"`
}

func (x *DeleteExerciseRequest) Reset() {
	*x = DeleteExerciseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExerciseRequest) ProtoMessage() {}

func (x *DeleteExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExerciseRequest.ProtoReflect.Descriptor instead.
func (*DeleteExerciseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteExerciseRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteExerciseRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteExerciseRequest) GetWorkoutId() uint64 {
	if x != nil {
		return x.WorkoutId
	}
	return 0
}

type DeleteExerciseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
}

func (x *DeleteExerciseResponse) Reset() {
	*x = DeleteExerciseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExerciseResponse) ProtoMessage() {}

func (x *DeleteExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExerciseResponse.ProtoReflect.Descriptor instead.
func (*DeleteExerciseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteExerciseResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteExerciseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExerciseTitleRecommendationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypingTitle string `protobuf:"bytes,1,opt,name=typingTitle,proto3" json:"typingTitle"`
}

func (x *ExerciseTitleRecommendationRequest) Reset() {
	*x = ExerciseTitleRecommendationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExerciseTitleRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseTitleRecommendationRequest) ProtoMessage() {}

func (x *ExerciseTitleRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseTitleRecommendationRequest.ProtoReflect.Descriptor instead.
func (*ExerciseTitleRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{6}
}

func (x *ExerciseTitleRecommendationRequest) GetTypingTitle() string {
	if x != nil {
		return x.TypingTitle
	}
	return ""
}

type ExerciseTitleRecommendationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status             uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Error              string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
	RecommendationList []*TitleRecommendation `protobuf:"bytes,3,rep,name=recommendationList,proto3" json:"recommendationList"`
}

func (x *ExerciseTitleRecommendationResponse) Reset() {
	*x = ExerciseTitleRecommendationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExerciseTitleRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseTitleRecommendationResponse) ProtoMessage() {}

func (x *ExerciseTitleRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseTitleRecommendationResponse.ProtoReflect.Descriptor instead.
func (*ExerciseTitleRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{7}
}

func (x *ExerciseTitleRecommendationResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExerciseTitleRecommendationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExerciseTitleRecommendationResponse) GetRecommendationList() []*TitleRecommendation {
	if x != nil {
		return x.RecommendationList
	}
	return nil
}

type Workout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId        uint64      `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Title         string      `protobuf:"bytes,3,opt,name=title,proto3" json:"title"`
	Description   string      `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	IsDone        bool        `protobuf:"varint,5,opt,name=is_done,json=isDone,proto3" json:"is_done"`
	AppointedTime int64       `protobuf:"varint,6,opt,name=appointed_time,json=appointedTime,proto3" json:"appointed_time"`
	CreatedAt     int64       `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     int64       `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	Exercises     []*Exercise `protobuf:"bytes,9,rep,name=exercises,proto3" json:"exercises"`
}

func (x *Workout) Reset() {
	*x = Workout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workout) ProtoMessage() {}

func (x *Workout) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workout.ProtoReflect.Descriptor instead.
func (*Workout) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{8}
}

func (x *Workout) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workout) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Workout) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Workout) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workout) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *Workout) GetAppointedTime() int64 {
	if x != nil {
		return x.AppointedTime
	}
	return 0
}

func (x *Workout) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Workout) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Workout) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

type Exercise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title       string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Description string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	IsDone      bool          `protobuf:"varint,4,opt,name=is_done,json=isDone,proto3" json:"is_done"`
	Repetitions []*Repetition `protobuf:"bytes,5,rep,name=repetitions,proto3" json:"repetitions"`
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{9}
}

func (x *Exercise) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exercise) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Exercise) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Exercise) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *Exercise) GetRepetitions() []*Repetition {
	if x != nil {
		return x.Repetitions
	}
	return nil
}

type Repetition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Weight float32 `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight"`
	Count  uint32  `protobuf:"varint,3,opt,name=count,proto3" json:"count"`
	IsDone bool    `protobuf:"varint,4,opt,name=is_done,json=isDone,proto3" json:"is_done"`
}

func (x *Repetition) Reset() {
	*x = Repetition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Repetition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repetition) ProtoMessage() {}

func (x *Repetition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repetition.ProtoReflect.Descriptor instead.
func (*Repetition) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{10}
}

func (x *Repetition) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Repetition) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Repetition) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Repetition) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

type TitleRecommendation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title"`
}

func (x *TitleRecommendation) Reset() {
	*x = TitleRecommendation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TitleRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleRecommendation) ProtoMessage() {}

func (x *TitleRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleRecommendation.ProtoReflect.Descriptor instead.
func (*TitleRecommendation) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{11}
}

func (x *TitleRecommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateWorkoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	AppointedTime int64  `protobuf:"varint,4,opt,name=appointed_time,json=appointedTime,proto3" json:"appointed_time"`
}

func (x *CreateWorkoutRequest) Reset() {
	*x = CreateWorkoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkoutRequest) ProtoMessage() {}

func (x *CreateWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkoutRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{12}
}

func (x *CreateWorkoutRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateWorkoutRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateWorkoutRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorkoutRequest) GetAppointedTime() int64 {
	if x != nil {
		return x.AppointedTime
	}
	return 0
}

type CreateWorkoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Error   string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
	Workout *Workout `protobuf:"bytes,3,opt,name=workout,proto3" json:"workout"`
}

func (x *CreateWorkoutResponse) Reset() {
	*x = CreateWorkoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkoutResponse) ProtoMessage() {}

func (x *CreateWorkoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkoutResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkoutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{13}
}

func (x *CreateWorkoutResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateWorkoutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateWorkoutResponse) GetWorkout() *Workout {
	if x != nil {
		return x.Workout
	}
	return nil
}

type WorkoutFilteringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Query  []byte `protobuf:"bytes,2,opt,name=query,proto3" json:"query"`
}

func (x *WorkoutFilteringRequest) Reset() {
	*x = WorkoutFilteringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkoutFilteringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutFilteringRequest) ProtoMessage() {}

func (x *WorkoutFilteringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutFilteringRequest.ProtoReflect.Descriptor instead.
func (*WorkoutFilteringRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{14}
}

func (x *WorkoutFilteringRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WorkoutFilteringRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type WorkoutFilteringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32     `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Error   string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
	Workout []*Workout `protobuf:"bytes,3,rep,name=workout,proto3" json:"workout"`
}

func (x *WorkoutFilteringResponse) Reset() {
	*x = WorkoutFilteringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkoutFilteringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutFilteringResponse) ProtoMessage() {}

func (x *WorkoutFilteringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutFilteringResponse.ProtoReflect.Descriptor instead.
func (*WorkoutFilteringResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{15}
}

func (x *WorkoutFilteringResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WorkoutFilteringResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkoutFilteringResponse) GetWorkout() []*Workout {
	if x != nil {
		return x.Workout
	}
	return nil
}

type WorkoutTitleRecommendationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypingTitle string `protobuf:"bytes,1,opt,name=typingTitle,proto3" json:"typingTitle"`
}

func (x *WorkoutTitleRecommendationRequest) Reset() {
	*x = WorkoutTitleRecommendationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkoutTitleRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutTitleRecommendationRequest) ProtoMessage() {}

func (x *WorkoutTitleRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutTitleRecommendationRequest.ProtoReflect.Descriptor instead.
func (*WorkoutTitleRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{16}
}

func (x *WorkoutTitleRecommendationRequest) GetTypingTitle() string {
	if x != nil {
		return x.TypingTitle
	}
	return ""
}

type WorkoutTitleRecommendationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status             uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Error              string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
	RecommendationList []*TitleRecommendation `protobuf:"bytes,3,rep,name=recommendationList,proto3" json:"recommendationList"`
}

func (x *WorkoutTitleRecommendationResponse) Reset() {
	*x = WorkoutTitleRecommendationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkoutTitleRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutTitleRecommendationResponse) ProtoMessage() {}

func (x *WorkoutTitleRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutTitleRecommendationResponse.ProtoReflect.Descriptor instead.
func (*WorkoutTitleRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{17}
}

func (x *WorkoutTitleRecommendationResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WorkoutTitleRecommendationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkoutTitleRecommendationResponse) GetRecommendationList() []*TitleRecommendation {
	if x != nil {
		return x.RecommendationList
	}
	return nil
}

type UpdateWorkoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Query  []byte `protobuf:"bytes,3,opt,name=query,proto3" json:"query"`
}

func (x *UpdateWorkoutRequest) Reset() {
	*x = UpdateWorkoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkoutRequest) ProtoMessage() {}

func (x *UpdateWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkoutRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateWorkoutRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWorkoutRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateWorkoutRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type UpdateWorkoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Error   string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
	Workout *Workout `protobuf:"bytes,3,opt,name=workout,proto3" json:"workout"`
}

func (x *UpdateWorkoutResponse) Reset() {
	*x = UpdateWorkoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWorkoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkoutResponse) ProtoMessage() {}

func (x *UpdateWorkoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkoutResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkoutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateWorkoutResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateWorkoutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateWorkoutResponse) GetWorkout() *Workout {
	if x != nil {
		return x.Workout
	}
	return nil
}

type DeleteWorkoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
}

func (x *DeleteWorkoutRequest) Reset() {
	*x = DeleteWorkoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkoutRequest) ProtoMessage() {}

func (x *DeleteWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkoutRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteWorkoutRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteWorkoutRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteWorkoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
}

func (x *DeleteWorkoutResponse) Reset() {
	*x = DeleteWorkoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWorkoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkoutResponse) ProtoMessage() {}

func (x *DeleteWorkoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_workout_pb_workout_workout_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkoutResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkoutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_workout_pb_workout_workout_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteWorkoutResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteWorkoutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_workout_pb_workout_workout_proto protoreflect.FileDescriptor

var file_pkg_workout_pb_workout_workout_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x2f, 0x70, 0x62,
	0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72,
	0x6b, 0x6f, 0x75, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x77,
	0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x7c, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x34, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x73, 0x65, 0x52, 0x08, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x22, 0x75,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x7c, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x34, 0x0a,
	0x08, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x08, 0x65, 0x78, 0x65, 0x72, 0x63,
	0x69, 0x73, 0x65, 0x22, 0x5f, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x65,
	0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x6f,
	0x75, 0x74, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78,
	0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x46, 0x0a, 0x22,
	0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x23, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73,
	0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x53, 0x0a, 0x12, 0x72, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x12, 0x72, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0xa0, 0x02, 0x0a, 0x07, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x65, 0x78,
	0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45,
	0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x09, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73,
	0x65, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x64, 0x6f,
	0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65,
	0x12, 0x3c, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x63,
	0x0a, 0x0a, 0x52, 0x65, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73,
	0x5f, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x44,
	0x6f, 0x6e, 0x65, 0x22, 0x2b, 0x0a, 0x13, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0x8e, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x78, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b,
	0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x22, 0x48, 0x0a, 0x17, 0x57,
	0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x7b, 0x0a, 0x18, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x31, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f,
	0x75, 0x74, 0x22, 0x45, 0x0a, 0x21, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x79,
	0x70, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x22, 0x57, 0x6f,
	0x72, 0x6b, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x53,
	0x0a, 0x12, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x12, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x78, 0x0a, 0x15, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x31, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x07, 0x77, 0x6f, 0x72,
	0x6b, 0x6f, 0x75, 0x74, 0x22, 0x3f, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f,
	0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xf5, 0x03, 0x0a,
	0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x55, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x24, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f,
	0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a,
	0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x12, 0x27, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x6f, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x83,
	0x01, 0x0a, 0x1a, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x32, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa5, 0x03, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x25, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x86, 0x01, 0x0a, 0x1b, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x32, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x75,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73,
	0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x76, 0x65, 0x6c,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x6f, 0x72,
	0x6b, 0x6f, 0x75, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_workout_pb_workout_workout_proto_rawDescOnce sync.Once
	file_pkg_workout_pb_workout_workout_proto_rawDescData = file_pkg_workout_pb_workout_workout_proto_rawDesc
)

func file_pkg_workout_pb_workout_workout_proto_rawDescGZIP() []byte {
	file_pkg_workout_pb_workout_workout_proto_rawDescOnce.Do(func() {
		file_pkg_workout_pb_workout_workout_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_workout_pb_workout_workout_proto_rawDescData)
	})
	return file_pkg_workout_pb_workout_workout_proto_rawDescData
}

var file_pkg_workout_pb_workout_workout_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pkg_workout_pb_workout_workout_proto_goTypes = []interface{}{
	(*CreateExerciseRequest)(nil),               // 0: WorkoutService.CreateExerciseRequest
	(*CreateExerciseResponse)(nil),              // 1: WorkoutService.CreateExerciseResponse
	(*UpdateExerciseRequest)(nil),               // 2: WorkoutService.UpdateExerciseRequest
	(*UpdateExerciseResponse)(nil),              // 3: WorkoutService.UpdateExerciseResponse
	(*DeleteExerciseRequest)(nil),               // 4: WorkoutService.DeleteExerciseRequest
	(*DeleteExerciseResponse)(nil),              // 5: WorkoutService.DeleteExerciseResponse
	(*ExerciseTitleRecommendationRequest)(nil),  // 6: WorkoutService.ExerciseTitleRecommendationRequest
	(*ExerciseTitleRecommendationResponse)(nil), // 7: WorkoutService.ExerciseTitleRecommendationResponse
	(*Workout)(nil),                             // 8: WorkoutService.Workout
	(*Exercise)(nil),                            // 9: WorkoutService.Exercise
	(*Repetition)(nil),                          // 10: WorkoutService.Repetition
	(*TitleRecommendation)(nil),                 // 11: WorkoutService.TitleRecommendation
	(*CreateWorkoutRequest)(nil),                // 12: WorkoutService.CreateWorkoutRequest
	(*CreateWorkoutResponse)(nil),               // 13: WorkoutService.CreateWorkoutResponse
	(*WorkoutFilteringRequest)(nil),             // 14: WorkoutService.WorkoutFilteringRequest
	(*WorkoutFilteringResponse)(nil),            // 15: WorkoutService.WorkoutFilteringResponse
	(*WorkoutTitleRecommendationRequest)(nil),   // 16: WorkoutService.WorkoutTitleRecommendationRequest
	(*WorkoutTitleRecommendationResponse)(nil),  // 17: WorkoutService.WorkoutTitleRecommendationResponse
	(*UpdateWorkoutRequest)(nil),                // 18: WorkoutService.UpdateWorkoutRequest
	(*UpdateWorkoutResponse)(nil),               // 19: WorkoutService.UpdateWorkoutResponse
	(*DeleteWorkoutRequest)(nil),                // 20: WorkoutService.DeleteWorkoutRequest
	(*DeleteWorkoutResponse)(nil),               // 21: WorkoutService.DeleteWorkoutResponse
}
var file_pkg_workout_pb_workout_workout_proto_depIdxs = []int32{
	9,  // 0: WorkoutService.CreateExerciseResponse.exercise:type_name -> WorkoutService.Exercise
	9,  // 1: WorkoutService.UpdateExerciseResponse.exercise:type_name -> WorkoutService.Exercise
	11, // 2: WorkoutService.ExerciseTitleRecommendationResponse.recommendationList:type_name -> WorkoutService.TitleRecommendation
	9,  // 3: WorkoutService.Workout.exercises:type_name -> WorkoutService.Exercise
	10, // 4: WorkoutService.Exercise.repetitions:type_name -> WorkoutService.Repetition
	8,  // 5: WorkoutService.CreateWorkoutResponse.workout:type_name -> WorkoutService.Workout
	8,  // 6: WorkoutService.WorkoutFilteringResponse.workout:type_name -> WorkoutService.Workout
	11, // 7: WorkoutService.WorkoutTitleRecommendationResponse.recommendationList:type_name -> WorkoutService.TitleRecommendation
	8,  // 8: WorkoutService.UpdateWorkoutResponse.workout:type_name -> WorkoutService.Workout
	12, // 9: WorkoutService.WorkoutService.Create:input_type -> WorkoutService.CreateWorkoutRequest
	20, // 10: WorkoutService.WorkoutService.Delete:input_type -> WorkoutService.DeleteWorkoutRequest
	18, // 11: WorkoutService.WorkoutService.Update:input_type -> WorkoutService.UpdateWorkoutRequest
	14, // 12: WorkoutService.WorkoutService.All:input_type -> WorkoutService.WorkoutFilteringRequest
	16, // 13: WorkoutService.WorkoutService.WorkoutTitleRecommendation:input_type -> WorkoutService.WorkoutTitleRecommendationRequest
	0,  // 14: WorkoutService.ExerciseService.Create:input_type -> WorkoutService.CreateExerciseRequest
	2,  // 15: WorkoutService.ExerciseService.Update:input_type -> WorkoutService.UpdateExerciseRequest
	4,  // 16: WorkoutService.ExerciseService.Delete:input_type -> WorkoutService.DeleteExerciseRequest
	6,  // 17: WorkoutService.ExerciseService.ExerciseTitleRecommendation:input_type -> WorkoutService.ExerciseTitleRecommendationRequest
	13, // 18: WorkoutService.WorkoutService.Create:output_type -> WorkoutService.CreateWorkoutResponse
	21, // 19: WorkoutService.WorkoutService.Delete:output_type -> WorkoutService.DeleteWorkoutResponse
	19, // 20: WorkoutService.WorkoutService.Update:output_type -> WorkoutService.UpdateWorkoutResponse
	15, // 21: WorkoutService.WorkoutService.All:output_type -> WorkoutService.WorkoutFilteringResponse
	17, // 22: WorkoutService.WorkoutService.WorkoutTitleRecommendation:output_type -> WorkoutService.WorkoutTitleRecommendationResponse
	1,  // 23: WorkoutService.ExerciseService.Create:output_type -> WorkoutService.CreateExerciseResponse
	3,  // 24: WorkoutService.ExerciseService.Update:output_type -> WorkoutService.UpdateExerciseResponse
	5,  // 25: WorkoutService.ExerciseService.Delete:output_type -> WorkoutService.DeleteExerciseResponse
	7,  // 26: WorkoutService.ExerciseService.ExerciseTitleRecommendation:output_type -> WorkoutService.ExerciseTitleRecommendationResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_workout_pb_workout_workout_proto_init() }
func file_pkg_workout_pb_workout_workout_proto_init() {
	if File_pkg_workout_pb_workout_workout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_workout_pb_workout_workout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExerciseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExerciseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExerciseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExerciseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExerciseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExerciseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExerciseTitleRecommendationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExerciseTitleRecommendationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exercise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Repetition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TitleRecommendation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkoutFilteringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkoutFilteringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkoutTitleRecommendationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkoutTitleRecommendationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWorkoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWorkoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWorkoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_workout_pb_workout_workout_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWorkoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_workout_pb_workout_workout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_workout_pb_workout_workout_proto_goTypes,
		DependencyIndexes: file_pkg_workout_pb_workout_workout_proto_depIdxs,
		MessageInfos:      file_pkg_workout_pb_workout_workout_proto_msgTypes,
	}.Build()
	File_pkg_workout_pb_workout_workout_proto = out.File
	file_pkg_workout_pb_workout_workout_proto_rawDesc = nil
	file_pkg_workout_pb_workout_workout_proto_goTypes = nil
	file_pkg_workout_pb_workout_workout_proto_depIdxs = nil
}
